name: Runs cypress tests (module 4)
on:
  push:
    paths:
    - '4-deploying/1-github-actions/cypress/**'
jobs:
  cypress:
    name: Execute cypress

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: npm install
        run: |
          npm install

      - name: run tests
        run: npm run --silent --prefix 4-deploying/1-github-actions/cypress start
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}