name: Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'
      - name: npm install
        run: |
          npm install
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm run --prefix 4-auditing/1-lighthouse lighthouse || echo "LHCI failed!"